### ISSUE TITLE
Pass op or op. Context to tokenRefreshNeeded

### ISSUE THREAD

**Issue by msalsbery** [larskarbo/trpc-token-refresh-link#1]
Feature request: Would it be useful to pass op or op.context in the tokenRefreshNeeded call? Would be handy for skipping the refresh on requests to endpoints that don't need credentials...

**Comment by epicmau5time** [comment]
I've made a pull request with the feature, hopefully it's merged

**Comment by larskarbo** [comment]
Fixed with #2
