### ISSUE TITLE
add to awesome trpc libs 

### ISSUE THREAD

**Issue by rafaferry** [larskarbo/trpc-token-refresh-link#3]
Awesome lib man, just what I needed.

You should ask for the TRPC team to endorse this lib on the https://trpc.io/docs/awesome-trpc libs list.

**Comment by larskarbo** [comment]
Thanks, that's a good idea! Would you mind helping me by adding a pr for the change here? https://github.com/trpc/trpc/blob/main/www/docs/main/awesome-trpc.mdx

**Comment by larskarbo** [comment]
https://github.com/trpc/trpc/pull/4776
